name = "TreeSitterHighlight"
uuid = "d012cbc0-9be0-4aad-9a84-80c4f029fdfc"
authors = ["Paul <paul@plutojl.org>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Wasmtime = "f519113a-1485-4b12-af44-dbf9b5a2f6b4"
tree_sitter_highlight_jll = "a99a7680-1b0c-57dd-b59a-79ab8f52c9a4"

[compat]
CEnum = "0.4"
julia = "1"
